# Generated by Django 3.0.6 on 2020-05-24 10:18

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, help_text='После сохранения автоматически меняет высоту картинки на 500px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=profile_user.models.generate_url_for_image, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_thumb',
            field=models.FileField(blank=True, help_text='МОЖНО НЕ ЗАПОЛНЯТЬ, генирируеться автоматически из "Главное изображение ЖК" с высотой картинки 300px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=profile_user.models.generate_url_for_image, verbose_name='Thumbnail Фото'),
        ),
    ]
