# Generated by Django 3.0.6 on 2020-05-24 12:36

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_auto_20200524_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(default=None, max_length=10, unique=True, verbose_name='Короткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='image_thumb',
            field=models.FileField(blank=True, help_text='<b style="color:red;font-size:10px;">МОЖНО НЕ ЗАПОЛНЯТЬ, генирируеться автоматически</b> из "Фото" с высотой картинки 300px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=profile_user.models.generate_url_for_image, verbose_name='Thumbnail Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_specialization', to='profile_user.Specialization', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_jobtitle', to='profile_user.JobTitle', verbose_name='Специализация'),
        ),
    ]
