# Generated by Django 3.0.6 on 2020-05-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_auto_20200524_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_jobtitle', to='profile_user.JobTitle', verbose_name='Должность'),
        ),
    ]
