# Generated by Django 3.0.6 on 2020-05-25 01:27

import commercial_real_estate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_location', '0002_auto_20200524_2220'),
        ('residential_real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория бизнеса',
                'verbose_name_plural': 'Категории бизнесов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('is_group_multiple_objs', models.BooleanField(default=False, help_text='Если нужно занести несколько помещений в одну карточку.', verbose_name='Сгруппировать несколько объектов')),
                ('use_contacts_fixed_agent', models.BooleanField(default=False, verbose_name='Использовать контакты Закреплённого(-ых) агента(-ов)')),
                ('cost_service', models.FloatField(blank=True, null=True, verbose_name='Стоимость услуг')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Продажа')),
                ('is_rent', models.BooleanField(default=False, verbose_name='Аренда')),
                ('area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь')),
                ('min_area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь от, м')),
                ('max_area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь до, м')),
                ('number_of_storeys', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Этажность здания')),
                ('several_floors', models.BooleanField(default=False, verbose_name='Недвижимость с несколькими этажами')),
                ('building_commercial_estate', models.BooleanField(default=False, help_text='Находиться в процессе строительства.', verbose_name='Строящее')),
                ('finished_commercial_estate', models.BooleanField(default=False, help_text='Построенное помещение.', verbose_name='Готовое')),
                ('rent_price_sq_m', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоимость аренды, руб/кв.м.')),
                ('rent_price_month', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоимость аренды, руб/мес.')),
                ('cost_of_sale', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу')),
                ('min_cost_of_sale', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу, от')),
                ('max_cost_of_sale', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу, до')),
                ('min_payback', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Окупаемость от, мес')),
                ('max_payback', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Окупаемость до, мес')),
                ('min_average_rental_rate', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Средняя арендная ставка от, руб/кв.м.')),
                ('max_average_rental_rate', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Средняя арендная ставка до, руб/кв.м.')),
                ('possible_income', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Возможный доход, руб/мес.')),
                ('year_construction', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год постройки')),
                ('kw', models.FloatField(blank=True, db_index=True, null=True, verbose_name='кВт')),
                ('min_kw', models.FloatField(blank=True, db_index=True, null=True, verbose_name='кВт, от')),
                ('max_kw', models.FloatField(blank=True, db_index=True, null=True, verbose_name='кВт, до')),
                ('comment_kw', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к "кВт"')),
                ('ceiling_height', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Высота потолков, м.')),
                ('min_ceiling_height', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Высота потолков от, м.')),
                ('max_ceiling_height', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Высота потолков до, м.')),
                ('comment_ceiling_height', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к "Высота потолков"')),
                ('parking', models.BooleanField(default=False, verbose_name='Наличие парковки')),
                ('min_parking', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Парковка от, шт.')),
                ('max_parking', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Парковка до, шт.')),
                ('comment_parking', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к "Парковка"')),
                ('main_image', models.FileField(blank=True, null=True, upload_to=commercial_real_estate.models.generate_url_for_image, verbose_name='Главное изображение')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_address', to='geo_location.Address', verbose_name='Адрес')),
                ('business_category', models.ManyToManyField(blank=True, default=None, related_name='comestate_businesscategory', to='commercial_real_estate.BusinessCategory', verbose_name='Категория бизнеса')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_city', to='geo_location.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Коммерческая недвижимость',
                'verbose_name_plural': 'Коммерческие недвижимости',
            },
        ),
        migrations.CreateModel(
            name='CommunicationSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Системы коммуникаций',
                'verbose_name_plural': 'Системы коммуникаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CookerHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вытяжка',
                'verbose_name_plural': 'Вытяжки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отделка коммерческой недвижимости',
                'verbose_name_plural': 'Отделки коммерческой недвижимости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelativeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Расположение',
                'verbose_name_plural': 'Расположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeCommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип коммерческой недвижимости',
                'verbose_name_plural': 'Типы коммерческой недвижимости',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeEntranceToCommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип входа в коммерческое помещение',
                'verbose_name_plural': 'Типы входов в коммерческое помещение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoCommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_on_video', models.URLField(blank=True, default=None, max_length=2000, null=True, verbose_name='Ссылка на видео')),
                ('add_text', models.CharField(blank=True, max_length=300, verbose_name='Доплнительный текст')),
                ('commercial_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_commercial_estate', to='commercial_real_estate.CommercialEstate', verbose_name='Коммерческая недвижимость')),
            ],
            options={
                'verbose_name': 'Видео Коммерческого помещения',
                'verbose_name_plural': 'Видео Коммерческого помещения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImagesCommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('image', models.FileField(blank=True, null=True, upload_to=commercial_real_estate.models.generate_url_for_image, verbose_name='Изображение')),
                ('commercial_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_commercial_estate', to='commercial_real_estate.CommercialEstate', verbose_name='Коммерческая недвижимость')),
            ],
            options={
                'verbose_name': 'Изображение Коммерческой недвижимости',
                'verbose_name_plural': 'Изображения Коммерческой недвижимости',
            },
        ),
        migrations.CreateModel(
            name='FloorPlansCommercialEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('image', models.FileField(blank=True, null=True, upload_to=commercial_real_estate.models.generate_url_for_image, verbose_name='Планировка')),
                ('commercial_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans_commercial_estate', to='commercial_real_estate.CommercialEstate', verbose_name='Коммерческая недвижимость')),
            ],
            options={
                'verbose_name': 'Планировка Коммерческой недвижимости',
                'verbose_name_plural': 'Планировки Коммерческой недвижимости',
            },
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='communication_systems',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_comsystems', to='commercial_real_estate.CommunicationSystems', verbose_name='Системы коммуникаций'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='cooker_hood',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_cookerhood', to='commercial_real_estate.CookerHood', verbose_name='Вытяжка'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_district', to='geo_location.District', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='finishing_property',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_finproperty', to='commercial_real_estate.FinishingProperty', verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='fixed_agent',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_fixedagent', to=settings.AUTH_USER_MODEL, verbose_name='Закреплённый агент'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='floor',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_floor', to='residential_real_estate.FloorInBuilding', verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_region', to='geo_location.Region', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='relative_location',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_relativelocation', to='commercial_real_estate.RelativeLocation', verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='residential_complex',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_rescomplex', to='residential_real_estate.ResidentialComplex', verbose_name='Жилой комплекс'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='type_commercial_estate',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_purpose', to='commercial_real_estate.TypeCommercialEstate', verbose_name='Тип коммерческой недвижимости'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='type_entrance',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_typeentrance', to='commercial_real_estate.TypeEntranceToCommercialEstate', verbose_name='Тип входа'),
        ),
    ]
