# Generated by Django 3.0.6 on 2020-05-25 02:17

import commercial_real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_real_estate', '0003_auto_20200525_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanscommercialestate',
            name='image_thumb',
            field=models.FileField(blank=True, help_text='МОЖНО НЕ ЗАПОЛНЯТЬ, генирируеться автоматически из "Главное изображение ЖК" с высотой картинки 300px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=commercial_real_estate.models.generate_url_for_image, verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='floorplanscommercialestate',
            name='image',
            field=models.FileField(blank=True, help_text='После сохранения автоматически меняет высоту картинки на 500px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=commercial_real_estate.models.generate_url_for_image, verbose_name='Изображение'),
        ),
    ]
