# Generated by Django 3.0.6 on 2020-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_real_estate', '0001_initial'),
        ('commercial_real_estate', '0004_auto_20200525_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestate',
            name='distance_to_metro',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Растояние до метро, м'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='metro_stations',
            field=models.ManyToManyField(blank=True, default=None, related_name='comestate_metrostations', to='residential_real_estate.NamesOfMetroStations', verbose_name='Название ближайщего метро'),
        ),
    ]
