# Generated by Django 3.0.6 on 2020-06-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_real_estate', '0006_auto_20200526_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialestate',
            name='basement',
            field=models.BooleanField(default=False, verbose_name='Подвал'),
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Цоколь'),
        ),
    ]
