# Generated by Django 3.0.6 on 2020-06-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_real_estate', '0007_auto_20200606_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бизнес центр',
                'verbose_name_plural': 'Бизнес центры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commercialestate',
            name='business_center',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comestate_buscenter', to='commercial_real_estate.BusinessCenter', verbose_name='Бизнес центр'),
        ),
    ]
