# Generated by Django 3.0.6 on 2020-05-24 13:02

from django.db import migrations, models
import django.db.models.deletion
import geo_location.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('main_image', models.FileField(blank=True, null=True, upload_to=geo_location.models.generate_url_for_image, verbose_name='Изображение')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NumHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Номер дома / корпуса')),
            ],
            options={
                'verbose_name': 'Номер дома',
                'verbose_name_plural': 'Номера домов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('main_image', models.FileField(blank=True, null=True, upload_to=geo_location.models.generate_url_for_image, verbose_name='Изображение')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Район')),
                ('subname', models.CharField(max_length=10, unique=True, verbose_name='Сокращённое название')),
                ('main_image', models.FileField(blank=True, null=True, upload_to=geo_location.models.generate_url_for_image, verbose_name='Изображение')),
                ('alt_attr', models.CharField(blank=True, max_length=300, verbose_name='img alt')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_city', to='geo_location.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_region', to='geo_location.Region', verbose_name='Область'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Адрес')),
                ('numhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_numhouse', to='geo_location.NumHouse', verbose_name='Номер дома / корпуса')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_street', to='geo_location.Street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес (Улица и Номер дома)',
                'verbose_name_plural': 'Адреса (Улицы и Номера домов)',
                'ordering': ['name'],
            },
        ),
    ]
