# Generated by Django 3.0.6 on 2020-06-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0002_auto_20200524_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id'], 'verbose_name': 'Город / Населенный пункт', 'verbose_name_plural': 'Города / Населенные пункты'},
        ),
    ]
